name: ddp
description: MeteorJS DDP library for Dart.
version: 0.0.2
author: haoguo <bard.guo@gmail.com>
homepage: https://github.com/haoguo/ddp
environment:
  sdk: ">=1.8.0 <3.0.0"

dependencies:
  mutex: ^1.0.1
  tuple: ^1.0.2
  sprintf: ^4.0.0

dev_dependencies:
  test: ^1.3.0