name: ddp
description: MeteorJS DDP library for Dart.
version: 0.0.13
author: haoguo <bard.guo@gmail.com>
homepage: https://github.com/haoguo/ddp
environment:
  sdk: ">=1.8.0 <3.0.0"

dependencies:
  tuple: ^1.0.2

dev_dependencies:
  test: ^1.3.0